title: New Venture Creation with ChatGPT
description: A guide on how to use ChatGPT for new venture creation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
